### PR TITLE
Proposed modifications to installation, hello world examples and h2d introduction

### PR DESCRIPTION
**Pull request by olichose123**
After having experimented for a couple of months with Heaps and realizing, when recommending this great engine to a friend of mine, that the documentation was not really adapted to newbies and that most things I knew I had figured out by reading the source, I decided to try to update some of the documentation to help new users start up with Heaps.

I upgraded the installation file, which still mentionned Haxe 4 as a release candidate, and expanded on some vscode and extension concepts for those who might not have used the IDE yet.

The Hello-Hashlink tutorial never really worked for me so I refactored it a bit to include how I start new projects. I also had to update Hello-World (the javascript target) to fit with it. Hello-Hasklink is not a bit more standalone, but I still list the changes from Hello-World in case it's useful.

Finally, I re-ordered things around for H2d-introduction in what I think is a more logical representation. The Object and the Scene are the most important concepts, then the visual stuff. I added examples for each concept and added the concept of the Bitmap.

I plan on updating other 2D stuff if this PR is quality enough for you. 

**Suggestion**: 
* The h2d documentation should have a different layout and different page names to better represent the learning curve of the engine
  * Introduction (as is)
  * Loading images (a new page, a dumbed-down version of _Resource Management_ for images, also include _Optimizing bitmaps_)
  * Drawables and Tiles (merge Drawable and Drawing Tiles)
  * Drawing shapes (the Drawing Graphics page)
  * Events and Interactions (as is)
  * Collision (new page on Bounds, Polygons, Rays, etc.)
  * Filters
  * Remove shaders for a better, complete shader page in Shaders section

### CODE REVIEW

**Comment by ncannasse** [comment]
Thanks for the contribution, greatly appreciated !
Documentation is one of the area where Heaps lacks the most, see related discussion here:
https://github.com/HeapsIO/heaps/issues/745#issuecomment-572956131

**Comment by Yanrishatum** [comment]
I don't agree on Hello Hashlink part where you suggest using `out/` directory for hl file. Because `res` is not copied over to `out`, it would cause the build to not work if ran from `out` as a working directory, since it can't access the resources directory.

**Comment by olichose123** [comment]
That's an interesting argument. I'm not sure I agree, for multiple reasons:
1.  Haxe compilation to different targets can produce a varying amount of output that should be in its own folder, or else it will mix with the source code and other folders that could be in the main directory. In other words, compiling directly into the main directory will clutter everything.
2. During development, a game is usually run from the working directory, which has no effect on the location of the compiled bytecode.
3. A game ready for deployment would have a main directory with an executable that points to binary files in a subdirectory, and resources in another. (./my_game.exe runs bin/game.hl and fetches resources fron res/...).
```
.
└── my_game
    ├── my_game.exe
    ├── bin/ (or out/ during development)
    │   └── (hashlink bytecode)
    └── res/
        └── (art and assets)
```
4. it's easier to exclude out/ in a gitignore or other ignore files than manually select output files of different targets (.js, .map, etc).

**Comment by ncannasse** [comment]
I agree with Pavel on this one. This is not the standard for Heaps to use
out directory. Thanks we are not C++ that outputs hundreds of files but a
single .hl that can be ignored.

**Comment by olichose123** [comment]
I'd argue that the [HXML documentation](https://haxe.org/manual/compiler-usage-hxml.html) uses an output directory called `bin` for output. Do you mean to change `out` for `bin` or forgo the `out` folder entirely and compile to the working dir?

**Comment by Yanrishatum** [comment]
I do understand the need in out, when generating more than one file, but here it's redundant by the most part. Production builds would have their own hxml/commands to compile, hence changing where it goes is fairly simple. It adds directory setup more complexity than necessary, and as I said - some people may miss the fact that running hl file directly would not work. It's not OpenFL with its own build system, which copies all assets to the compiled directory.
For reference:
HL: One .hl file
HLC: Lots of .c files and such, but it's advised to be used for consoles, and you compile that separately in any case, as you can't test it on PC. Not much point in using it for development.
JS: 2 to 3 files: index.html, game js and .map files.

I can't agree that it clutters root directory that much. And yes, I argue forgoing `out` / `bin`, since it's redundant for HL and introduces extra complexity. HXML documentation provides an example, it does not make it a rule, that resulting files should go into the bin directory. On the contrary, 99.9% of the times I target JS - I compile into root directory. Good example of a need in `bin` directory is something like HIDE, where it does have numerous extra files as output.

**Comment by olichose123** [comment]
I yield, you all have good arguments. I'll make a new pull request with the changes tomorrow.

**Pull request merged**
